server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///home/yesmi/eclipse-workspace/learning/confsvr/config/licensingservice